name : Test
on:
  push:
    branches: 
      - feature-1
  workflow_dispatch:
    inputs:
      sa_enable:
        description: 'Load SA App'
        required: true
        default: 'true'

jobs:
  build_web:
    runs-on: ubuntu-latest

    steps:
      - if: github.event.inputs.sa_enable == 'true'
        name: Load SA App
        run: echo "yarn build"
      - if: github.event.inputs.sa_enable == 'false'
        name: Unload Load SA App
        run: echo "yarn build:Disabled"
        
