name : Test
on:
  push:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      ssa_enable:
        description: 'Load SA App'
        required: true
        default: 'true'
        type: choice
        options:
        - 'true'
        - 'false'

jobs:
  build_web:
    runs-on: ubuntu-latest

    steps:
      - name: print
        run: echo "${{github.event.inputs.sa_enable}}"
      - if: github.event.inputs.sa_enable == '' || github.event.inputs.sa_enable == 'true'
        name: Load SA App
        run: echo "yarn build"
      - if: github.event.inputs.sa_enable == 'false'
        name: Unload Load SA App
        run: echo "yarn build:Disabled"
        
