name : Test
on:
  push:
    branches:
      - main

jobs:
  conditional:
    runs-on: ubuntu-latest
    steps:
      - if: github.event.inputs.publish_artifacts == 'true'
        name: Publish Artifacts
        run: echo "Hello"
        
