name : Test
on:
  workflow_dispatch:
    inputs:
      sa_enable:
        description: 'Load SA App'
        required: true
        default: 'true'

jobs:
  build_web:
    runs-on: ubuntu-latest

    steps:
      - if: github.event.inputs.sa_enable == 'true'
        name: Load SA App
        run: echo "I am Happy"
        
