name: Start EC2 machine in AWS

on:
  workflow_dispatch:
  schedule:
    # Runs "At 09:00 AM on every day-of-week from Monday through Friday. Below time is mentioned in UTC time zone" (see https://crontab.guru)
    - cron: '30 03 * * 1-5'

jobs:
  start-rds:
    name: Start EC2 Machine
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BAHMNI_AWS_ID }}
          aws-secret-access-key: ${{ secrets.BAHMNI_AWS_SECRET }}
          aws-region: ap-south-1

      - name: Start EC2 Instance
        run: |
          aws ec2 start-instances --instance-ids ***REMOVED***
