name: Start EC2 machine in AWS

on:
  workflow_dispatch:
  schedule:
    # Runs "At 09:00 AM IST on every day-of-week from Monday through Friday. Below time is mentioned in UTC time zone" (see https://crontab.guru)
    - cron: '30 6 * * 1-5'

env:
  INSTANACE_ID: ***REMOVED***

jobs:
  start-rds:
    name: Start EC2 Machine
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BAHMNI_AWS_ID }}
          aws-secret-access-key: ${{ secrets.BAHMNI_AWS_SECRET }}
          aws-region: ap-south-1

      - name: Start EC2 Instance
        run: aws ec2 start-instances --instance-ids $INSTANACE_ID
      - name: extract private key
        run: 'echo "$SSH_KEY" > speech-assistant.pem'
        env:
          SSH_KEY: ${{secrets.SPEECH_ASSISTANT_PEM}}
      - name: Sleep for 60 seconds
        run: sleep 60s
      - name: extract publicDnsName value
        run: |
          publicDnsName=$(aws ec2 describe-instances --instance-ids $INSTANACE_ID | jq '.Reservations[0].Instances[0].PublicDnsName' | tr -d '"')
          echo '::set-output name=publicDnsName::'$publicDnsName
        id: get-publicDnsName
      - name: start bahmni and speech-assistant application
        run: |
          sudo ssh -o "StrictHostKeyChecking no" -i "speech-assistant.pem" ec2-user@${{ steps.get-publicDnsName.outputs.publicDnsName }} <<EOF
          sudo service docker start
          docker-compose -f bahmni-package/bahmni-docker/docker-compose.yml up -d
          docker-compose -f speech-assistant-package/docker-compose.yml up -d
