name: Deploy Speech-Assistant-Package
on:
  push:
    branches:
      - main

env:
  INSTANCE_ID: ***REMOVED***

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BAHMNI_AWS_ID }}
          aws-secret-access-key: ${{ secrets.BAHMNI_AWS_SECRET }}
          aws-region: ap-south-1
      - name: extract private key
        run: 'echo "$SSH_KEY" > speech-assistant.pem'
        env:
          SSH_KEY: ${{secrets.SPEECH_ASSISTANT_PEM}}
      - name: extract PublicIpAddress value
        run: |
          publicIpAddress=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID | jq '.Reservations[0].Instances[0].PublicIpAddress' | tr -d '"')
          echo '::set-output name=publicIpAddress::'$publicIpAddress
        id: get-publicIpAddress
      - name: print public ip address
        run: echo ${{ steps.get-publicIpAddress.outputs.publicIpAddress }}
      - name: public ip address
        run: |
          jq --arg ip_add "${{ steps.get-publicIpAddress.outputs.publicIpAddress }}" '.Changes[].ResourceRecordSet.ResourceRecords[].value = $ip_add' aws/example.json > recordset
          echo $recordset | jq '.'
          
