name: Deploy Speech-Assistant-Package
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BAHMNI_AWS_ID }}
          aws-secret-access-key: ${{ secrets.BAHMNI_AWS_SECRET }}
          aws-region: ap-south-1
      - name: extract private key
        run: 'echo "$SSH_KEY" > speech-assistant.pem'
        env:
          SSH_KEY: ${{secrets.SPEECH_ASSISTANT_PEM}}
      - name: extract PublicIpAddress value
        run: |
          publicIpAddress=$(aws ec2 describe-instances --instance-ids ${{secrets.BAHMNI_INSTANCE_ID}} | jq '.Reservations[0].Instances[0].PublicIpAddress' | tr -d '"')
          echo '::set-output name=publicIpAddress::'$publicIpAddress
        id: get-publicIpAddress
      - name: print public ip address
        run: echo ${{ steps.get-publicIpAddress.outputs.publicIpAddress }}
      - name: public ip address
        run: |
          jq '.Changes[].ResourceRecordSet.ResourceRecords[].Value = "${{ steps.get-publicIpAddress.outputs.publicIpAddress }}"' aws/route53/speech.mybahmni.in.json > recordset 
          aws route53 change-resource-record-sets --hosted-zone-id ${{ secrets.BAHMNI_AWS_HOSTED_ZONE_ID }} --change-batch file://recordset
          
